name: messanger
description: Messenger for the exchange of information, opinions and private discussions in a completely confidential manner, developed for the SAFEROOM application
homepage: https://github.com/ali-github-acount/messanger
issue_tracker: https://github.com/ali-github-acount/messanger/issues
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.2
  http: ^0.13.5
  path: ^1.8.2
  device_preview: ^1.1.0
  hive: ^2.2.3
  messanger_server:  
    git:
      url: https://messenger_server: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@github.com/ali-github-acount/messanger_server.git
      ref: main
dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
